
import __ASTRO_IMAGE_IMPORT_1AY0lb from "../../assets/a.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthird-post.md";
import __ASTRO_IMAGE_IMPORT_ZhpiB0 from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FQ42.md";
import __ASTRO_IMAGE_IMPORT_Z24ly0P from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frobbert.md";
import __ASTRO_IMAGE_IMPORT_ZjD12a from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhans.md";
import __ASTRO_IMAGE_IMPORT_Z1wyKBH from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjohan.md";
import __ASTRO_IMAGE_IMPORT_ZulDpU from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.md";
import __ASTRO_IMAGE_IMPORT_HPQjx from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackaton.md";
import __ASTRO_IMAGE_IMPORT_Zly7IV from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frosa.md";
import __ASTRO_IMAGE_IMPORT_CUDgk from "../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecond-post.md";
export default new Map([["../../assets/a.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthird-post.md", __ASTRO_IMAGE_IMPORT_1AY0lb], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FQ42.md", __ASTRO_IMAGE_IMPORT_ZhpiB0], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frobbert.md", __ASTRO_IMAGE_IMPORT_Z24ly0P], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhans.md", __ASTRO_IMAGE_IMPORT_ZjD12a], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjohan.md", __ASTRO_IMAGE_IMPORT_Z1wyKBH], ["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.md", __ASTRO_IMAGE_IMPORT_ZulDpU], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackaton.md", __ASTRO_IMAGE_IMPORT_HPQjx], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frosa.md", __ASTRO_IMAGE_IMPORT_Zly7IV], ["../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsecond-post.md", __ASTRO_IMAGE_IMPORT_CUDgk]]);
		