
import __ASTRO_IMAGE_IMPORT_Zt7aNs from "../../assets/a.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnils.md";
import __ASTRO_IMAGE_IMPORT_ZhpiB0 from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FQ42.md";
import __ASTRO_IMAGE_IMPORT_Z24ly0P from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frobbert.md";
import __ASTRO_IMAGE_IMPORT_Z2x5kX2 from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsmash1.md";
import __ASTRO_IMAGE_IMPORT_Z2x5cWE from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsmash2.md";
import __ASTRO_IMAGE_IMPORT_Z26Xfdb from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftwyw1.md";
import __ASTRO_IMAGE_IMPORT_Z26X7cN from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftwyw2.md";
import __ASTRO_IMAGE_IMPORT_ZImPrN from "../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvoorhoede.md";
import __ASTRO_IMAGE_IMPORT_ZjD12a from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhans.md";
import __ASTRO_IMAGE_IMPORT_Z1wyKBH from "../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjohan.md";
import __ASTRO_IMAGE_IMPORT_Z1JAKyy from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcssday1.md";
import __ASTRO_IMAGE_IMPORT_Z1JACyb from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcssday2.md";
import __ASTRO_IMAGE_IMPORT_Zx81n1 from "../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkilian.md";
import __ASTRO_IMAGE_IMPORT_HPQjx from "../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackaton.md";
import __ASTRO_IMAGE_IMPORT_Zly7IV from "../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frosa.md";
import __ASTRO_IMAGE_IMPORT_l0mCm from "../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fppk.md";
export default new Map([["../../assets/a.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnils.md", __ASTRO_IMAGE_IMPORT_Zt7aNs], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FQ42.md", __ASTRO_IMAGE_IMPORT_ZhpiB0], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frobbert.md", __ASTRO_IMAGE_IMPORT_Z24ly0P], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsmash1.md", __ASTRO_IMAGE_IMPORT_Z2x5kX2], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsmash2.md", __ASTRO_IMAGE_IMPORT_Z2x5cWE], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftwyw1.md", __ASTRO_IMAGE_IMPORT_Z26Xfdb], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftwyw2.md", __ASTRO_IMAGE_IMPORT_Z26X7cN], ["../../assets/blog-placeholder-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fvoorhoede.md", __ASTRO_IMAGE_IMPORT_ZImPrN], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhans.md", __ASTRO_IMAGE_IMPORT_ZjD12a], ["../../assets/blog-placeholder-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fjohan.md", __ASTRO_IMAGE_IMPORT_Z1wyKBH], ["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcssday1.md", __ASTRO_IMAGE_IMPORT_Z1JAKyy], ["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcssday2.md", __ASTRO_IMAGE_IMPORT_Z1JACyb], ["../../assets/blog-placeholder-3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkilian.md", __ASTRO_IMAGE_IMPORT_Zx81n1], ["../../assets/blog-placeholder-4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackaton.md", __ASTRO_IMAGE_IMPORT_HPQjx], ["../../assets/blog-placeholder-5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Frosa.md", __ASTRO_IMAGE_IMPORT_Zly7IV], ["../../assets/blog-placeholder-about.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fppk.md", __ASTRO_IMAGE_IMPORT_l0mCm]]);
		